### PR TITLE
feat: new validators (is_mime_type, is_iso6391)

### PR DESCRIPTION
**Pull request by ShriekinNinja**
feat: added is_mime_type and tests 
feat: added is_iso6391 and tests
updated readme

### CODE REVIEW

**Comment by theteladras** [comment]
> Hi, @theteladras 👋
> 
> Thank you for this repo and all the work you've put to it.
> 
> Is it still active?

Its still active. Thanks for contributing!

I'll be doing a review on it.

**Comment by theteladras** [comment]
@ShriekinNinja It looks good to me, just make sure to update the MINOR version to 18 in `setup.py`. This will ensure that the changes will be deployed to pypi.

**Comment by ShriekinNinja** [comment]
Done.
Thank you !

**Comment by theteladras** [comment]
Merging! Thanks @ShriekinNinja!

**Pull request merged**
